name: SFTP Deploy

on:
  push:
    branches:
      - main  # or the branch you want to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Initialize submodules

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Rsync deploy
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_TARGET_DIR: ${{ secrets.SFTP_TARGET_DIR }}
        run: |
          rsync -avz --delete -e "sshpass -p $SFTP_PASSWORD ssh -o StrictHostKeyChecking=no" src/ $SFTP_USERNAME@$SFTP_SERVER:$SFTP_TARGET_DIR
